<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Contactos - Login</title>

        <link href="css/estilo.css" type="text/css" rel="stylesheet">
        <link href="css/materialize.min.css" type="text/css" rel="stylesheet">
        <link rel="shortcut icon" href="img/favicon.png" />

        <script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>        
        <script type="text/javascript" src="js/materialize.min.js"></script>
        <script type="text/javascript" src="js/app.js"></script>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper">
              <a href="./" class="brand-logo center">Contactos</a>
            </div>
        </nav>

        <div class="row">
            <div class="section">
            <h3 class="header center">Inicia sesión</h3>
            <div class="col s8 offset-s2">
                <form action='login.php' method='post' class="col s8 offset-s2">
                    <div class="row">
                        <div class="input-field col s12">
                          <input id="username" name="username" type="text" class="validate">
                          <label for="username">Usuario</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                          <input id="password" name="password" type="password" class="validate">
                          <label for="password">Clave</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <span><?php echo getErrorLogin(); ?></span>
                        </div>
                    </div>
                    <div class="row">
                        <button class="btn waves-effect waves-light center" type="submit" name="action">Acceder
                            <i class="mdi-content-send right"></i>
                        </button>
                    </div>
                </form>
            </div>
            </div>
        </div>
    </body>
</html>