<!DOCTYPE html>
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Contactos - Subir Foto</title>

  <!-- <link href="css/estilo.css" type="text/css" rel="stylesheet"> -->
  <link href="css/materialize.min.css" type="text/css" rel="stylesheet">
  <link rel="shortcut icon" href="img/favicon.png" />

  <script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>        
  <script type="text/javascript" src="js/materialize.min.js"></script>
  <script type="text/javascript" src="js/app.js"></script>
</head>

<body>
  <nav>
    <div class="nav-wrapper">
      <a href="./" class="brand-logo center">Contactos</a>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="section">
        <div class="col s8 offset-s2">
          <div class="card blue-grey darken-1 center">
            <div class="card-content white-text">
              <span class="card-title">Error al subir la Foto</span>
              <p><?php echo $error;?></p>
            </div>
            <div class="card-action">
              <a href="./">Volver</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
