    <div class="row">
        <div class="section">
            <div class="col s8 offset-s2">
                <form action='subirArchivo.php' method='post' enctype="multipart/form-data" class="col s8 offset-s2">
                    <div class="file-field input-field">
                        <input type="hidden" name="mail" value='<?php echo $_GET['mail']; ?>' />
                        <input class="file-path validate" type="text"/>
                        <div class="btn">
                            <span>Foto</span>
                            <input name="file" type="file" id="file" />
                        </div>
                    </div>
                    <div class="row">
                        <button class="btn waves-effect waves-light center" type="submit" name="submit">
                            Grabar <i class="mdi-content-send right"></i>
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
